production:
  adapter       : 'sqlite'
  location      : 'db'
  database      : 'production.db'
  auto_upgrade  : true

development:
  adapter       : 'sqlite'
  location      : 'db'
  database      : 'development.db'
  auto_migrate  : true  

test:
  adapter       : 'sqlite'
  location      : 'db'
  database      : 'test.db'
  auto_migrate  : true


# PostgreSQL
# adapter       : 'postgres'
# location      : 'localhost'
# database      : 'dbname'
# auto_migrate  : true
# auto_upgrade  : true

# MongoDB
# adapter       : 'mongo'
# location      : 'localhost'
# database      : 'dbname'

# MySQL
# adapter       : 'mysql'
# location      : 'localhost'
# database      : 'dbname'